### ISSUE TITLE
Anonymous peer Review: Anonymize "breadcrumbs" and "collection" level information for this feature in HDV and install in Production

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#10950]
### Request:
- To utilize this feature in HDV, the breadcrumbs and collection level information for any deposit need to be anonymized.

### Tasks:

- [ ] Anonymize breadcrumbs and collection level info
- [ ] Add to HDV production

### Related issue: 
- [ ] https://github.com/IQSS/dataverse-HDV-Curation/issues/592

### Question:
1. Is this a feature update, or can this be an installation-level (local) change? *Just for our knowledge

**Comment by sbarbosadataverse** [comment]
@sekmiller just an FYI that I updated the tasks associated with this issue to ensure we anonymize the proper fields for the HDV use case: https://github.com/IQSS/dataverse.harvard.edu/issues/119#issuecomment-900312388

**Comment by sekmiller** [comment]
![Screen Shot 2024-11-14 at 4 55 46 PM](https://github.com/user-attachments/assets/e4146009-9dea-4faa-a89c-494c8397ac78)


This shows what the dataset home page will look like for anonymous preview - there are no breadcrumbs and the collection name is not visible. You will be able to see the installation custom header, but that's all.

**Comment by sekmiller** [comment]
@sbarbosadataverse, Omer is currently looking at this for QA. I'll ask him to put it on Dataverse Internal if you'd like to take a look.

**Comment by sbarbosadataverse** [comment]
> * Anonymous peer Review: Add to HDV production dataverse-HDV-Curation#592

@sekmiller I missed this message and would like to look at this in test, and I think @kmika11 should also have a look
