### ISSUE TITLE
MyData (Data Related to Me) To Do List

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#2302]
Dependency:  #2038 (see **Production dependencies** below)

----
This is divided into two broad checklists related to the mydata branch:

- [x] Retrieving Data and putting into the JSON document
 - [x] #2328 - **BUG** with 1 result in count but no solr doc
 - [x] #2303, clean up SearchServiceBean (currently using SearchServiceBeanMyData)
 - [x] #2305, Fix pager logic to display 5 pages at a time
 - [x] #2304, Get additional card attributes
   - [ ] QA for root dataverse card
 - [x] #2306, Get counts for publication status
 - [x] #2314  Show only available roles
 - [x] #2382 - deaccession statuses for datasets
 - ~~[ ] Add file tags to final cards~~ move to #2410
 - ~~[ ] Add affiliations to final dataverse card -- **single query** to grab all affils.~~ move to #2410
 - [x] #2316 Exclude harvested info **single query** go get harvested dv's ```harvestingdataverseconfig```
- [x] UI/UX display / functionality (need some time with Mike/Liz to make action items)
 - ~~[ ] logic for displaying correct icons for file cards.~~ move to #2410
 - [x] #2317, overall checkbox functionality
   - ~~[x] #2307, dvobject checkbox functionality to match homepage~~ 
 - [x] #2312, UX question on publication status checkboxes
 - [x] card content, follow balsamiq mock-up (no citations)
 - [x] #2308, Test with production data (for responsiveness) 
 - [x] #2325, add "is_restricted" to solr cards (mydata)
  - related to #2311 (below) where users have 100s, 1000s objects
 - [x] #2309, add to tab on account page. Do this **after** #2308 is found to perform with a full db
 - [x] #2320 paging, remove pager and use 'more/infinite' scroll for inititial testing
     - currently pager working but scroll has bugs

---

#### Production dependencies
 - [ ] #2038, solr indexing for entityId 
 - [ ] #2311, update jetty header size to allow larger queries 
    - current prod data for sonia is 30k query

(in progress)

**Comment by raprasad** [comment]
![account_-_root_dataverse](https://cloud.githubusercontent.com/assets/1036060/8577134/acdd53f6-2574-11e5-9161-2e693db56470.png)

**Comment by raprasad** [comment]
Last issues moved to #2410 and #2411

**Comment by kcondon** [comment]
Issues were tested as individual tickets, closing
