### ISSUE TITLE
homepage performance

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#2472]
This is an umbrella ticket for:

- [ ] #2474 Homepage Cleanup ```#1``` - Efficient retrieval of Card Attributes
- [ ] #2475 Homepage Cleanup ```#2``` - Efficient Retrieval of File Images and Icons 
- [ ] #2476 Homepage ```#3``` - For Searching and Filtering, Return JSON instead of rendered HTML

----

### Current State

The homepage is still quite expensive in terms of queries, load time, etc.  What can be made more efficient as well as cached?

#### Example Scenario

localhost, 20 dataverses, 58 datasets, 373 files

#### Example Scenario SQL Query counts
-  Not logged in:
  -  plain vanilla homepage: 873
  -  clicking the "Files" facet: 5065
-  Logged In:
  -  plain vanilla homepage: 1123
  -  clicking the "Files" facet: 5068

### Impact
Multiply these numbers by 100 hits on the homepage, 200 hits, 1000 hits ... and you have a slow homepage (and other slow pages) as seen in google analytics below

----

#### "bad/ugly" Homepage: 7.93 seconds (up from 5.57 seconds)

- 32.14% of page loads: 3 to 7 seconds
- 43% of page loads: 7+ seconds (mostly 7-13 seconds)

#### "ugly" All pages: 13.36 seconds (down from 15.11)

- 30.64% of page loads: 3-7 seconds
- 33.49% : 7+ seconds (mostly 7-13 seconds)
	- 19.48%: 13+ seconds 
	- 12.59%: 21+ seconds

#### "good" MyData Page*:  0.93 seconds (less than 1 sec)

- 631 visits, only .96% of traffic

----
replacement for #2096 

Overview of 3 suggestions: https://docs.google.com/document/d/1EQItOOD3wNHBy-Pk4ufSznxpdQdto_3xmD1aFWV9DoM/edit

Card attributes (solr vs. db):
https://docs.google.com/a/harvard.edu/spreadsheets/d/1L8_4LU-8SG3Ubycfei5n2ufh1u-Lpszo4rghJMD2BFI/edit?usp=sharing

**Comment by bencomp** [comment]
I don't understand why #2096 had to be closed in favour of this issue?

**Comment by raprasad** [comment]
@bencomp - I added recent google analytics to the issue--trying to get it back in the milestone queue...

**Comment by raprasad** [comment]
Here are the top line results keeping in mind that the MyData approach was run under conditions worse than it should ever encounter if used for the homepage:


### Test 1: 50 Users, Dataverse + Dataset Cards + Stats
- HomePage:  1.40 seconds per page
- My Data: 0.55 seconds per page
- **MyData Time savings**: 0.85 seconds per page

### Test 2: 50 Users,  File Cards + Stats
- HomePage:  6.00 seconds per page
- My Data: 0.50 seconds per page
- **MyData Time savings:** 5.50 seconds per page

### Test 3**: 150 Users, 50% Dataverse + Dataset Cards + Stats  / 50% File Cards + Stats

- HomePage:  15.00 seconds per page
- My Data: 1.10 seconds per page
- **MyData Time savings:** 13.90 seconds per page

** Test 3 was run with and without “boosted” database settings.  In the “unboosted” (current live) mode, the homepage throughput dropped to 0.5 requests per second (RPS) while MyData handled 12 RPS.  In the boosted mode, the homepage handled 3 RPS and MyData stayed about the same.
[test-summary-2015-1019.pdf](https://github.com/IQSS/dataverse/files/16846/test-summary-2015-1019.pdf)

**Comment by pdurbin** [comment]
> the top line results

It looks like https://github.com/IQSS/dataverse-helper-scripts/commit/665808382671c49f275c67f4fab6963f656e2463 and https://github.com/IQSS/dataverse-helper-scripts/commit/2008e97df0b5e8ed9a846a22ab5eb56fa128c036 were the main commits for running these tests. I'm linking to them here so any developer can re-run the tests before and after making the proposed changes.

**Comment by kcondon** [comment]
Significant homepage performance changes were made, closing this for now. Can reopen if performance is deemed unacceptable in the future.
