### ISSUE TITLE
Widgets: Dataset Pg Widget

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2499]
Currently only two widgets exist: 
1) Dataverse + Dataset listing
2) Search box

Need to determine additional widgets (such as dataset page and file page ones) as well as improve the current widgets to be more responsive and have more features (e.g.-facets).

**Comment by eaquigley** [comment]
Related to #2498, #1011, #2090, #2469

**Comment by posixeleni** [comment]
See also #1203 which is a deliverable we need to complete for a grant funded project

**Comment by mheppler** [comment]
As the comments above show, a lot of improvements and new widget features already have development issues created. There isn't an issue for the dataset page yet, so I am narrowing the scope of this ticket to just that feature by changing the title.

**Comment by mheppler** [comment]
Reviewed this issue with @scolapasta and discussed [possible dynamic solutions](http://stackoverflow.com/questions/18098641/jsf-dynamic-template-selection-through-manage-bean) that would allow the dataset pg to be displayed in the widgets using a UI template specific to the widgets and not the full-featured layout of the `dataverse_template.xhtml`. This solution needs to be scalable so that not only the dataset pg, but also the dataverse, file and any other future pages can also use this new widget template.

**Comment by mheppler** [comment]
**Dataset Page**
- [x] Add “Widgets” option to “Edit” button
- [x] New citation block layout to make it stand out a little more
  - [x] Create new include for the citation block
  - [x] Full citation, with persistentUrl link, opens in new window
  - [x] Cite Data button (changed from “Download Citation”)
  - [x] BibTex no longer downloads, but displays in browser
- [x] Metadata HTML links in compound field values open in new window

**Dataset Widgets Admin Page**
- [x] Widget code available for published data only
  - [x] No widget code generated before published (“Why widgets…” messaging)
- [x] Help text with link to User Guides
- [x] Code available for Dataset “Full” and Dataset Citation widgets
- [x] “Done” button returns to dataset pg
- [x] Apply bug fix for User Access/Permissions #2841

**Dataset “Full” Widget #2499**
- [x] Published data only
  - [x] No widget code generated before published (“Why widgets…” messaging)
- [x] Dataverse branding w/ “Data is stored at…” msg, link to installation #2469
- [x] Displays a slimmer/leaner layout intended for the widget, not full Dataverse layout intended for desktop browsers
  - [x] YES: breadcrumbs, msg block, contact author button, title, citation, files, metadata, terms tabs
  - [x] NO: header, footer, metrics block, link/share buttons, edit button, metadata summary block, versions tab
- [x] “Log in” link in footer to access admin features on full Dataverse installation
- [x] Breadcrumbs #2090
  - [x] Links to parent dataverse and anything higher in the hierarchy opens in a new window
- [x] Navigation (general, see use cases for more specific…)
  - [x] Request Access, new page opens with full Dataverse layout in new window
  - [x] Download+Guestbook popup displays within widget

**Dataset Citation Widget**
- [x] New citation block layout to make it stand out a little more
  - [x] Create new include for the citation block
- [x] Full citation, with persistentUrl link, opens in new window
- [x] Cite Data button (changed from “Download Citation”)
  - [x] BibTex no longer downloads, but displays in browser
- [x] Data Citation Standards msg + link, shortened to “Learn about…”
- [x] Dataverse branding w/ “Data is stored at…” msg, link to installation #2469

**Dataset “persistentUrl” Forwarding**
- [x] Dataverse Theme + Widgets Admin Page
  - [x] Opt-in via Advanced Options at the dataverse level only
  - [x] Validation for Personal Website URL format
  - [x] Success msg
- [x] Update URL’s in DataCite
- [x] Citation servlet
- [x] iFrame Landing Page
  - [x] Banner/bar with “If the site below does not load...” msg
  - [x] Link to Dataverse installation, close msg “X” icon forwards to external site
  - [x] Automatic delayed forward to external site (example), with counter (example)
  - [x] DOI passed as query parameter in URL to widget

**Comment by kcondon** [comment]
OK, works as described, closing.
