### ISSUE TITLE
WorldMap connection (umbrella ticket)

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#2546]
This ticket is a placeholder for mapping Dataverse files via the WorldMap.  The two main updates are:
  1. Mapping of tabular files (picking up work left off in March)
  1. ~~Using a service account to accces the WorldMap API~~
  1. ~~Removing Geoconnect from the picture which involves consolidating/rewriting code both within  WorldMap (merge-tabular-api branch) and Dataverse~~

---

~~Reference doc: https://goo.gl/u7eiTm~~

Initial checklist
- [x] #2611 WorldMap, use decorator that allows API auth
   - login_required decorator currently used that redirects to a web page rather than returning a 401
   - [x] #2615 - move shapefile test from geoconnect to WorldMap (test_shapefile_import.py)
   - [x] move classify test from geoconnect to WorldMap (test_classfiy_layer.py)
- [x] update WorldMap shapefile and tablejoin APIs
  - [x] nixed.  keeing the separate package ~~rationalize and perhaps rename the shared_dataverse_information package~~ ~~integrate shared_dataverse_information package pertaining to WorldMap directly into WorldMap (e.g. Geoconnect is going away)~~
- [ ] restructure geoconnect ```view_mapit_incoming_token64``` to:
  - [ ] check if worldmap already has this layer
      - e.g. don't needlessly retrieve file from DV
  - [ ] _maybe_ skip shapefile validation--since it's already baked into DV  
- [x] update geoconnect to use new decorator
  - [x] allow service account login from geoconnet to from WorldMap
- ~~[ ] Move Geoconnect UI functionality to Dataverse~~
- [ ] update documentation

**Comment by raprasad** [comment]
closing.  replacing with updated tickets
