### ISSUE TITLE
Reorganize and improve Installation Guide based on proposal from community

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#2884]
As I mentioned to @scolapasta yesterday, I'd like to take a swing at improving the Installation Guide based on the [Dataverse 4 Installation Guide Reorganization Proposal](https://docs.google.com/document/d/1GLky44JbtCNhGuavLXGEP8WPNdjbyHNxalEGjR78MaA/edit?usp=sharing) that the community has been iterating and commenting on ever since [it was announced](https://groups.google.com/d/msg/dataverse-community/qujUFJDYXG0/0BhECCp0HQAJ) on the mailing list.

I'm also conscious that @kcondon especially has opened individual issues related to the Installlation Guide and I'll try to address as many of these as is reasonable. These are the ones I'm aware of. Please note that some of these will **not** be closed as part of this issue because some of them aren't strictly about documentation alone. I'll put a checkbox next to the ones that I plan to have QA take a look at since I think I've at least partially addressed it:

- [x] #1406 System Config: Set proper startup scripts and order of startup for test/dev vms.
- [x] #1696 "Admin Dataverse" - Improve This Display Name, Other Attributes
- [x] #2211 Create Documentation for Super Users in User Guide
- [ ] #2212 Guides: Update TwoRavens documentation
- [x] #2234 Guides: Solr config should come from installer rather than GitHub
- [x] #2283 Installation and/or administration guide should list configuration options
- [x] #2287 Documentation: Add info on configuring Google Analytics to installer's guide.
- [x] #2289 Installation Guide: Incomplete postgres config info prevents installation.
- [x] #2311 update jetty header http size (mydata branch)
- [x] #2321 Installation Guide: Updates from tickets sent to RT
- [x] #2330 Documentation: Create Harvard Dataverse architecture schematic, publish to dataverse.org
- [x] #2401 Installation Guide: Tell users to start solr before running the installer, until installer includes Solr.
- [x] #2402 Installation Guide: Fix various typos.
- [x] #2405 Installation Guide: Add information that jq is required to run the installer.
- [x] #2415 File Ingest Limiter: Document file size limiter in the administration? section of the guides.
- [ ] #2477 Migration: Document and clean up script to update persistent id record target url.
- [ ] #2492 documentation: geoconnect keeps a list of 'registered dataverses'
- [x] #2521 Installation: use -server rather than -client JVM option for Glassfish
- [ ] #2593 User Guide: Add information on deleting datasets, dataverses and destroy command
- [x] #2617 Documentation: Add guidance on server size and managing file activity limits.
- [ ] #2619 Error 'declaration of the element "jhoveConfig" could not be found'
- [x] #2628 Upgrade Glassfish to 4.1.1 (mention it can't be used yet)
- [x] #2632 Installation Guide: Document how to configure DOI and Handles.
- [x] #2640 Installation Guide: Provide sample glassfish start up script
- [x] #2661 Installation Guide: Add all possible setting table settings and values to doc.
- [x] #2663 System Email: Default value for system email seems to be support@thedata.org, an out of date email domain.
- [x] #2817 Mention Vagrant in the Installation Guide
- [ ] #2848 Documentation: Document various temp directories used by Dataverse

I'll create a branch and start builds with Jenkins so we can start to see how the Installation Guide looks but for now I'm pushing a preview periodically to at http://dvn-vm1.hmdc.harvard.edu/tmp/issues/2884/build/html/installation/intro.html

**Comment by pameyer** [comment]
Looks good to me so far.  

Two suggestions:
 - The install url (postgresl.org) and repo name (EPEL) don't match up for postgresl pre-req.
 - jq (which is an install script dependency) isn't mentioned in prerequisites; on CentOS6 this can be supplied by EPEL.

**Comment by pdurbin** [comment]
89e3a3f is the first of what will probably be many commits to the 2884-install-guide-reorg branch I just created. I'll continue to push updates to http://dvn-vm1.hmdc.harvard.edu/tmp/issues/2884/build/html/installation/intro.html for now I guess. Comments are welcome on that commit or at http://chat.dataverse.org or in comments here or wherever. There are still lots of good ideas in the [Dataverse 4 Installation Guide Reorganization Proposal](https://docs.google.com/document/d/1GLky44JbtCNhGuavLXGEP8WPNdjbyHNxalEGjR78MaA/edit?usp=sharing) and tickets above that I plan to incorporate. Maybe not all of them though. It's a slog writing docs.

**Comment by pdurbin** [comment]
I just set up builds at http://guides.dataverse.org/en/2884-install-guide-reorg/installation so we can preview the docs.

The branch being used for these builds is https://github.com/IQSS/dataverse/tree/2884-install-guide-reorg

I'll send a pull request when I think the branch is good enough for @kcondon and others to look at it.

**Comment by pdurbin** [comment]
I made a pull request at #2895 so I'll send this parent ticket to QA as well but the pull request has better information than this issue does about what actually made it into the pull request.

Oh, and @pameyer I fixed both those issues. See #2405 for the jq one. And now it says to install standard postgres from yum. Thanks!

**Comment by kcondon** [comment]
Phil, this looks great and was a lot of work. Thanks. I think we can close this and open tickets for specific issues or feedback.
