### ISSUE TITLE
tabular checklist

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#2934]
- [x] join map
  - [x] complete join
  - [x] completely failed join
      - [x] no rows message?
  - [x] partial join
      - [x] partial row match
- [x]  delete layer (reuse shp code)
- [x]  classify layer (reuse shp code)
- [x] lat/lng map
- [x] Worldmap, tablejoin delete isn't dropping the view

---

- [x] SERIOUS: csvkit will convert strings to numeric, even if they are quoted.  no way to force it to stay string

---

- [x] confirm delete button
- [ ] modal box for unmapped rows
- [ ] clickable preview columns
- [ ] threshold of "bad rows"?
- [x] enable/disable
  - [x] tabular - message on page
  - [x] shapefiles - message on page
- [x] get a proper abstract in for the table joins
- [x] breadcrumb/title updates for tabular

---

- [x] worldmap
    - [x]new branch
    - [x] update requirements for shared-dataverse-information

**Comment by raprasad** [comment]
Moving last 3 items to new ticket
