### ISSUE TITLE
Installation Guide improvements following rewrite for 4.2.4

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#2944]
In #2884 I spent several days rewriting the Installation Guide and I was very pleased to see #2895 merged in. My changes can be seen at http://guides.dataverse.org/en/4.2.4/installation

I'm opening this issue to start a list of items that we didn't get to and new items that have come up:
- [x] #2212 Guides: Update TwoRavens documentation
- [x] #2311 Explain that you need to [add rather than update](https://github.com/IQSS/dataverse/issues/2311#issuecomment-179307101) `requestHeaderSize` in jetty.xml for Solr (fixed in 49217a0)
- [ ] #2477 Migration: Document and clean up script to update persistent id record target url.
- [ ] #2492 documentation: geoconnect keeps a list of 'registered dataverses'
- [ ] #2593 Guides: Add information on deleting datasets, dataverses and destroy command
- [ ] #2619 Error 'declaration of the element "jhoveConfig" could not be found'
- [ ] #2848 Documentation: Document various temp directories used by Dataverse
- [x] Document new `:ZipDownloadLimit` setting added in 4.2.4 for #2686
- [ ] Document how https://dataverse.harvard.edu has Solr "boosting" in place to improve search results per #1928 
- [x] Document Institution-wide Shibboleth groups developed in #1401 (fixed in https://github.com/IQSS/dataverse/tree/2939-shib )
- [x] Typo: "Proceed to the Prerequisites section will help you get ready to run the Dataverse installation script." at http://guides.dataverse.org/en/4.2.4/installation/prep.html (fixed in b59295f)
- [x] #2980 Emphasize the need to set the `:SystemEmail` or you will not be able to send mail: http://irclog.iq.harvard.edu/dataverse/2016-03-01#i_31933 (fixed in https://github.com/IQSS/dataverse/tree/4.3-installer-improvements )
- [x] #2981 Documentation: DOI configuration, persistent id options, installer default need clarification (fixed in https://github.com/IQSS/dataverse/tree/24-add-DataCite-DOI-Support )
- [x] Explain that rather than using `asadmin`, one can edit `domain.xml` but that this requires restarting Glassfish. See https://github.com/IQSS/dataverse/issues/2632#issuecomment-196507472 (Done already at http://guides.dataverse.org/en/4.2.4/installation/config.html#jvm-options )
- [x] `:StatusMessageText` has not been documented.
- [ ] Provide guidance on making backups. See https://help.hmdc.harvard.edu/Ticket/Display.html?id=234104
- [x] Typo: "indentifier" at http://guides.dataverse.org/en/4.3/installation/prep.html#architecture-and-components . Fixed in 91efe09
- [x] `curl -X PUT -d builtInS3kretKey http://localhost:8080/api/admin/settings/:BuiltinUsers.KEY` should not have a colon. Fixed in 91efe09
- [x] changing `:SolrHostColonPort` requires a Glassfish restart. Fixed in 91efe09.
- [ ] Update troubleshooting section to explain that `javax.persistence.NoResultException: getSingleResult() did not retrieve any entities.` means that the root dataverse could not be created: https://groups.google.com/d/msg/dataverse-community/xq1le9c8RmQ/0yhYe4dLLQAJ
- [ ] Update http://guides.dataverse.org/en/4.3.1/installation/installation-main.html#troubleshooting to mention how restarting Glassfish can help. See https://help.hmdc.harvard.edu/Ticket/Display.html?id=236419 . '"Inconsistent module state" [usually] means "keep restarting glassfish and redeploying" until it works. If it's still not working after 3 restarts, delete the entire contents of the "domain1/generated" directory, and keep restarting.'
- [ ] Provide default values, when applicable, for database settings and JVM options.
- [ ]  Consider adding useful links about Shibboleth federations. The InCommon feed contains IdPs from all over the world: https://spaces.internet2.edu/display/InCFederation/List+of+IdP+Display+Names . In addition, this R&S category view is nice: https://spaces.internet2.edu/display/InCFederation/Research+and+Scholarship+Entities .
- [ ] Update Shibboleth section to explain how to use SimpleSamlPhp: https://groups.google.com/d/msg/dataverse-community/PXHKNX6m-eU/eheWD4-3AAAJ
- [ ] Update Shibboleth section to explain how to use OneLogin: https://help.hmdc.harvard.edu/Ticket/Display.html?id=241355#txn-4832160
- [ ] #3061 Documentation: Add info on passing log in credentials to configured SMTP server. 
- [ ] #3112  Explain how to configure Google Analytics
- [x] remove superfluous true from `:SignUpUrl` Fixed in 91efe09.

People with edit access to this issue description should feel free to add additional items. People without edit access are welcome to leave comments.

**Comment by pdurbin** [comment]
@djbrooke this is the issue I mentioned about some known issues with the Installation Guide. As we discussed, let's create a new branch called something like "2944-install-guide" where we can start making commits.

**Comment by djbrooke** [comment]
@pdurbin - sounds good. Thanks for the overview! I'll plan to create separate issues and respective branches for the other guides (as/if needed).

**Comment by tomck** [comment]
Two suggestions for the install guide, prerequisites page:

1. Under glassfish, note that port 4848 issues might be connected to the hosts file. http://stackoverflow.com/a/17171641/6338845
2. Under Solr, the user is in the wrong directory to execute java -jar start.jar at the time it's suggested, they need to be ../../.. to run that.

**Comment by pdurbin** [comment]
@tomck just a heads up that fixed the start.jar thing in 91efe09. Thanks for reporting that. I'm not sure exactly what to write for the other thing about the hosts file. Please do feel free to make a pull request.

**Comment by pdurbin** [comment]
In 375e4b8 I documented `:StatusMessageText`. Closing. If people open new issues for some of this other stuff, great. We're working in small chunks. No zombie issues like this one. 😄
