### ISSUE TITLE
Meta issue: remove merged branches from GitHub repository

### ISSUE THREAD

**Issue by bencomp** [IQSS/dataverse#3113]
It appears that there are many branches in the IQSS/dataverse GitHub repository that have been merged into the master branch already:
```
ben:dataverse ben$ git branch -r --merged iqss/master
  iqss/1520-guides-navbar-fix
  iqss/1837-persistent-id-in-dataset-api
  iqss/2027-perm-perf
  iqss/2221-new-harvested-file-cards
  iqss/24-add-DataCite-DOI-Support
  iqss/2606-citation-date
  iqss/2686-2907-bugfixpatch-424
  iqss/2722-handle-Restricted-File-download
  iqss/2726-download-as-rdata
  iqss/2833-configurable-message-on-publish
  iqss/2871-batch-downloads-improvements
  iqss/2875-remove-extra-datasetversion-columns
  iqss/2914-worldmap-token
  iqss/2957-tab-mapping
  iqss/2965-dataset-card-links
  iqss/2966-4.0notification
  iqss/4.0.1
  iqss/4.0.2
  iqss/4.2
  iqss/HEAD -> iqss/master
  iqss/change-4.2.4-to-4.3
  iqss/feb-16-ux-fixes
  iqss/legacy
  iqss/master
```

Could you remove these to keep the repository (and local clones) clean? Well, not the `HEAD` and `master` of course!

**Comment by pdurbin** [comment]
"master" is on the list above but we don't plan to delete it. This issue about documenting the new pull request process is related: #2863.

**Comment by bencomp** [comment]
I had noticed that `master` is on the list, just like `HEAD`, and had edited the comment. Thanks for noticing, @pdurbin :)

**Comment by pdurbin** [comment]
I vote to close this issue in favor of documenting that developers are responsible for deleting branches they've created, as I mentioned at https://github.com/IQSS/dataverse/issues/2863#issuecomment-249937353

**Comment by mheppler** [comment]
[Git Clean: Delete Already-Merged Branches](http://stevenharman.net/git-clean-delete-already-merged-branches)

**Comment by mheppler** [comment]
Complete list (in reverse chronological order) of remote, merged branches that have been removed:
- [x] 2914-worldmap-token
- [x] feb-16-ux-fixes
- [x] 2686-2907-bugfixpatch-424
- [x] 2722-handle-Restricted-File-download
- [x] 2221-new-harvested-file-cards
- [x] 2871-batch-downloads-improvements
- [x] 1520-guides-navbar-fix
- [x] 2965-dataset-card-links
- [x] 2726-download-as-rdata
- [x] 2966-4.0notification
- [x] 2833-configurable-message-on-publish
- [x] 2027-perm-perf
- [x] 2875-remove-extra-datasetversion-columns
- [x] 2957-tab-mapping
- [x] 2606-citation-date
- [x] 1837-persistent-id-in-dataset-api
- [x] 24-add-DataCite-DOI-Support
- [x] change-4.2.4-to-4.3
- [x] 2391-file-edit-tags
- [x] 3046-add-dataverse-categories
- [x] 3015-userguideupdates
- [x] update-tsv-text
- [x] subjects-list-alpha
- [x] change-4.3-to-4.3.1
- [x] 2670-guestbook-response-display-download
- [x] 3091-shib-ui
- [x] fix-guestbook-merge
- [x] 3141-json-err
- [x] 3049-accout-notification
- [x] 2469-widgets
- [x] 3147-widgets-docs
- [x] change-4.3.1-to-4.4
- [x] 2746-testable-commands
- [x] 3223-widget-footer
