### ISSUE TITLE
For Dataverse-created maps, link BARI-worldmap credentials

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#3469]
## Background
  - BARI user has credentials for:
     1. Dataverse
     2. WorldMap
  - These are different credentials for completely separate systems with no common auth--at least in the near future

### Part I
  - BARI user logs into Dataverse (DV credentials)
  - BARI user maps a data file via the Dataverse-WorldMap connection
     - Normally, these map layers are owned by a Dataverse service account.  (This service account is a "normal" WorldMap account)
      - In this case, ownership permissions for the new layer should _also_ be given to the BARI WorldMap user
  - BARI users logs out of Dataverse

### Part II
  - BARI user logs into WorldMap
  - BARI user owns his/her Dataverse-created map layers and can work with the layers as needed
     - edit, delete, etc
  - Question: Does the view of a styled/updated layer get sent back to Dataverse?

## Implementation

A workaround will be determined in a meeting.  One example:

- For map creation requests against the WorldMap API, the request already includes the DV username
- Could create a WorldMap table that maps DV usernames to WorldMap users.  e.g.

| DV username/immutable id | WorldMap Username |
| ------------- |-------------| 
| bari_dataverse     | bari_worldmap | 
| bari_grad_student     | bari_worldmap | 

   - If a match is found, permissions for the new layer are also given to the WorldMap users
   - In scenario above, for map layers created my dataverse users ```bari_dataverse``` or ```bari_grad_student```, the full editing permissions will be given to the WorldMap user ```bari_worldmap```
   - The permission table could be extended to give map layer permissions to multiple users.  e.g. ```bari_grad_student``` creates a new map layer via Dataverse.  Full editing permissions could be given to the WorldMap user ```bari_worldmap2``` as well as ```bari_worldmap```.  e.g.:

| DV username/immutable id | WorldMap Username |
| ------------- |-------------| 
| bari_grad_student     | bari_worldmap | 
| bari_grad_student     | bari_worldmap2 |

**Comment by raprasad** [comment]
As per 11/22 conversation with Dan, this will be part of tabular mapping.  Use cases necessitating WorldMap access to the Dataverse-created layers:
  - Creating additional styles via WorldMap
  - Changing column labels

**Comment by raprasad** [comment]
- build vagrant file around these install steps:
  - https://github.com/cga-harvard/cga-worldmap

**Comment by raprasad** [comment]
- fyi: 50%+ of effort trying to get dev. environment set up.

**Comment by raprasad** [comment]
- [x] add DataversePermissionLink model (done in last commit)
- [ ] check DataversePermissionLink at API endpoints
  - [ ] shape
  - [ ] lat/lng
  - [ ] tab join

**Comment by raprasad** [comment]
- views.py
   - ajax_map_permissions
    - set_map_permissions
       - Map m.set_user_level(user, level)

**Comment by raprasad** [comment]
- previous commits have perms working for tabular lat/lng and shapefiles
- e.g. If the dataverse username is linked to a WorldMap username, the Dataverse-created map is editable by additional WorldMap users

**Comment by raprasad** [comment]
admin for linking account usernames:

![mozilla_firefox](https://cloud.githubusercontent.com/assets/1036060/23527273/4f78b1d6-ff63-11e6-96c3-d53edc4fce3e.png)
![mozilla_firefox](https://cloud.githubusercontent.com/assets/1036060/23527282/5d1ebfc4-ff63-11e6-8f35-4a0d06c030fe.png)

**Comment by raprasad** [comment]
Example of "linked users" added as editors on a WorldMap page:

![nhcrime_2014_08_9_tab_-_geonode](https://cloud.githubusercontent.com/assets/1036060/23527339/85f995c2-ff63-11e6-84d9-b0fbda6f744f.png)

**Comment by raprasad** [comment]
last check in, for table join...

**Comment by raprasad** [comment]
- [ ] remove UserObjectRoleMappings when table join deleted

**Comment by raprasad** [comment]
- retest with prod-like settings mimicking db sharding

**Comment by raprasad** [comment]
pull request has been made: https://github.com/cga-harvard/cga-worldmap/pull/211

**Comment by raprasad** [comment]
pull request has been merged...

**Comment by raprasad** [comment]
moved to WorldMap production

**Comment by raprasad** [comment]
WorldMap prod. errors occurring. Appears that new model not synced--e.g. new table not created in db.  (Is likely cause for geoconnect seen this morning when setting up heroku).   Have message into wm.

**Comment by raprasad** [comment]
New table now created.  Basic test working as expected with extra permissions being added.

**Comment by raprasad** [comment]
Everything working.  In addition to the error above, there was older, incomplete test data in prod. WorldMap throwing errors.   This can go to @kcondon after #3024 moves.

**Comment by kcondon** [comment]
Found a couple issues:
1. An as currently designed issue where the linked world map user does not see file in owned maps workspace and so cannot easily find it from within Worldmap. This also happens if user and map created entirely on Worldmap so it is their design. Mentioning it here since it also affects our proposed workflow integration. Design may need updating.

2. Intermittent internal server error when viewing generated Map on World map or when editing layer on world map and saving as linked user.

**Comment by raprasad** [comment]
Updated:
  - Checking with Ben on (1)
  - (2) appears to be resolved.  Was likely WorldMap server in bad state

**Comment by raprasad** [comment]
- Regarding issue (1) above from @kcondon, this is expected behavior.
  - Better functionality _does exist_ in the new version of GeoNode.  e.g. The linked user will be able to easily find layers on which she/he has an editor/administrator role.
  - When WorldMap is updated to the lastest GeoNode the end of the year, the functionality will be available--unless there is urgent user interest to have it now.
