### ISSUE TITLE
Integration with PSI Tools Overview

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#4063]
The attached diagram gives an overview of the following issues:

- [ ] IQSS/dataverse#4060 - Integration with PSI Tools (private data sharing interface) (1 of 3) 
- [ ] IQSS/dataverse#4061 - Integration with PSI Tools (private data sharing interface) (2 of 3) 
- [ ] IQSS/dataverse#4062 - Integration with PSI Tools (private data sharing interface) (3 of 3) 

Each of the issues above contains a portion of the overall workflow diagram below:

---

<img width="928" alt="psi_workflow_02_pdf__page_1_of_4_" src="https://user-images.githubusercontent.com/1036060/29184659-ed9d4486-7dd4-11e7-9539-da92719d7b8f.png">

**Comment by pdurbin** [comment]
What was PSI is now OpenDP (well, DP Creator for the web interface).

Should we close this in favor of the following issue?

- #9007

**Comment by susobaleato** [comment]
I would suggest reaching out James first, then proceed if no 
objection.

Philip Durbin ***@***.***> writes:

> What was PSI is now OpenDP (well, DP Creator for the web 
> interface).
>
> Should we close this in favor of the following issue?
>
> * #9007
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this 
> thread.


-- 
Suso Baleato - PhD Political Science < Computational Analysis
https://susobaleato.eu/ | gpg: 0x5BC0F044

**Comment by pdurbin** [comment]
Closing in favor of this:

- https://github.com/IQSS/dataverse-pm/issues/91
