### ISSUE TITLE
Metadata Fields > Edit Dataverse General Information - Various bugs and other UX unpleasantries

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#5441]
While reviewing the bug fix in #3924 for the Metadata Fields checklist on the Edit Dataverse General Information pg, I came across another known bug that was not resolved in that pull request. Upon further digging through the backlog, I discovered there were other known issues. This new issue aims to consolidate all of those various issues into one general FIX ME.

- [x] Add Dataset: Throws exception when on dataverse create, inherit metadata blocks is unchecked. #5613 (FIXED in v4.17)

- [x] ~Deselect/uncheck "Use metadata fields from Root", check/select a custom metadata block, click "Save Changes", go back and check/select "Use metadata fields from Root" again, see "Reset Modifications" confirmation popup, click "Continue" btn, popup closes and the edit form is automatically saved and you're returned to dataverse pg with success msg~  #3427/#4474 (FIXED in v 4.10)

- [ ] Hide/uncheck metadata field in custom block resets previously changed "Required" radio btn selection #1030

- [ ] Select/check custom metadata block, click "View fields + set as hidden, required, or optional" to open preview panel, deselect/uncheck same custom metadata block and preview panel remains open #1198

- [ ] Hide/uncheck metadata field in custom block, then change another field to "Required" by clicking the radio btn, click "Done" OR just click "Save Changes" and the second "Required" change is lost #2015

- [ ] Create a new dataverse, Deselect/uncheck "Use metadata fields from Root", select/check custom metadata block, click "View fields + set as hidden, required, or optional" to open preview panel, clicking "Done" btn does not close it #3175

- [ ] [FIXED?] Select/check custom metadata block, make "Required" radio btn selection, click "Save Changes", go back to Edit Dataverse General Information and select/check "Use metadata fields from Root", then "Save Changes", and again go back to Edit Dataverse General Information, does not show latest change back to root metadata fields  #2846

- [ ] [CLOSE? Bad data state?] Citation Metadata block is uncheck, plus other strange Demo bugs with Edit Dataverse General Information pg #4026

- [ ] [CLOSE? Not going to change?] Deselect/uncheck "Use metadata fields from Root" when you select/check another custom metadata block #1473

These issues have all been confirmed to still exist in the latest and greatest `develop` branch, unless otherwise noted. A few issues have also been included to close as either being fixed, non-reproducible, or something we aren't going to change at this time.
