### ISSUE TITLE
Truncate methods: checksums, long summary metadata fields 

### ISSUE THREAD

**Issue by TaniaSchlatter** [IQSS/dataverse#6685]
**Design Doc**
- Truncate + Toggle Content Display ([Google Drive](https://docs.google.com/document/d/1osxGz7jUZBiW23_rjUEUjKgnN4M4c57aTovyetXIrOA/edit#))

**Related Issues**
- Long (e.g. SHA-512) fixity checksums are too long for display #5210
- ~Handle long strings in the UI #6578~
- email verify icon overlaps email address #4484
- Display when assigning a role #5350
- Dataset Description: Doesn't wrap when there are no spaces #1634
- Dataverse - Description text truncated #1249

**Mockups**
- https://sketch.cloud/s/90bO0/a/bxvrlj/play

**Questions**
- Can we pick one format and use for all checksum types, or do we need to show different numbers of characters for different types?
    - The various checksum formats supported by the system are UNF, MD5, SHA-1, SHA-256, SHA-512, which vary from 32 to 512 characters in length... we should one scalable solution to display all the various config options consistently (@mheppler 👋)

**To-Do's**
- [x] create a list of content types (will require different scalable solutions)
    - checksum (..., display full string, and copy to clipboard)
    - textarea block, e.g. dataset desc, notes (open/close toggle)
    - long strings, e.g. account email #6578
- [x] review characteristics: what we want to do, and how
- [ ] potentially break into separate issues and close this one
- [ ] confirm/refine design solutions - plan to apply in scalable "site-wide" way
- [ ] identify widgets to use – some trial and error in code

**Comment by mheppler** [comment]
Last week, I updated my PR #7312 to apply truncation code to the checksums and UNF's on the dataset pg, as requested in #5210. This week, @landreev is helping to investigate issue #5215 in order to apply this feature to UNF's on the dataverse pg for the file search result cards, as I have already applied the feature to the checksums.

In addition to truncating long checksum strings, that PR applies a new attribute to the file dataTable on the dataset pg, that was discovered in an [answer on Stack Overflow](https://stackoverflow.com/a/38582318). By adding `tableStyle="min-width:100%;width:auto;"` to the dataTable, it no longer cuts off long strings when the overflow is hidden by the width of containing table cell. This will help solve some of the issues outline in #6578.

Will solve some of the other UI issues in separate PR's from the checksum PR, as there is already a lot going on in that one. Any additional responsive UI cleanup efforts will outlined here.

**Comment by mheppler** [comment]
Dataset description with HTML example: https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/M4ZGXP&version=1.0

**Comment by mheppler** [comment]
There is a list of related issues in the original comment above. A lot has been done in various efforts to resolve these issues, and I just wanted to get an update on them here...

- Long (e.g. SHA-512) checksums #5210 ... this was resolved in PR #7312
- Account email verified label overlap #4484 ... this issue was resolved in the PR #7516 for issue #3438
- Manage Permissions assign role label and description cleanup #5350 ... this issue was resolved in PR #7615

**NOTE:** I have closed issue **Handle long strings in the UI #6578** as that only had one outstanding issue, which is also being tracked in this issue.

There are two remaining issues that are very related and might be able to be resolved in one effort...

- Dataset Description: Doesn't wrap when there are no spaces #1634
- Dataverse - Description text truncated #1249

Those issues will continued to be tracked in this issue. Updates to follow.

**Comment by mheppler** [comment]
Progress tracking outline...

_WHAT TO TRUNCATE_
    - descriptions more than 500 characters
    - HTML including img, table, pre, etc
    - long strings (CSS word-break? overflow?)

_HOW TO TRUNCATE_
    - JS https://github.com/pathable/truncate
    - CSS (long strings??) https://getbootstrap.com/docs/3.4/css/#less-mixins-truncating ++ https://stackoverflow.com/questions/6222616/with-css-use-for-overflowed-block-of-multi-lines
    - scalable "truncate" class added to content container objects??

_HOW TO TOGGLE_
    - open/close? "Read more [+]" ... "Read less [-]"??
    - scroll to metadata tab > (full) description field??

_HOW IS IT ACCESSIBLE/RESPONSIVE_
    - content width, 700px, 50-75 characters https://baymard.com/blog/line-length-readability
    - jsoup (#1320) add responsive img class from bootstrap ++ add link target=_blank ++ noopener #4717

**Comment by mheppler** [comment]
Initial attempts at truncating descriptions with HTML worked, but were buggy. When testing on additional sample descriptions from production, they went from buggy to broken. Testing other plugins proved equally buggy, broken or did not support HTML.

Back to the drawing board. Investigating CSS-only methods like [line-clamp](https://caniuse.com/css-line-clamp) that have spotty browser support. I believe all the heavy lifting is done here, which is why I created the draft PR of the initial attempt. Just need to swap out the one plugin/snippet related to the truncation/clamping or whatever other method is out there. After much research, I can say there is no one "BEST" solution for this feature.

**Comment by mheppler** [comment]
Line-clamping wasn't all it was cracked up to be either. Reverse engineered a "Read more..." button I found in the wild on the internet for the cleanest (partial) solution yet... yay, me...

<img width="1152" alt="Screen Shot 2021-03-02 at 3 55 54 PM" src="https://user-images.githubusercontent.com/687227/109713899-c7497b00-7b6f-11eb-8bf9-a51b23b15984.png">
