### ISSUE TITLE
Analytics - Event tracking code not capture all the btn clicks

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#6938]
Here are is the current list of known analytics event tracking issues for the new action button UI (#6684) on the file and dataset pg. Changes to fix these will require release notes for sysadmins to update their installation's analytics code if they use event tracking code provided in the Installation Guide.

**FILE PG**
- [x] btn-explore, access file btn
- btn-compute ??
- btn-preview ??

**DATASET PG**
- [x] btn-download w/dropdown file table header
- [x] btn-download w/dropdown file table row (tabular)
- [x] btn-explore, access dataset btn
- btn-compute ??
- btn-preview ??

Will review with @qqmyers on any changes as QDR is also currently running the analytics event tracking code.

**Comment by mheppler** [comment]
Revised the sample analytics event tracking code provided in the guides. Provided @qqmyers the code to review. This should resolve tracking issues in the new UI as well as the 4.20 version of the UI with dropdown menu options clicks not getting tracked.

- add new `#actionButtonBlock .btn-access-dataset + ul.dropdown-menu` selector to the `getFileId` function to track clicks in the new 5.0 “Access Dataset” btn with dropdown menu
- add new `.btn-download.dropdown-toggle + ul.dropdown-menu li a` selector to the download, explore, compute and preview btns in order to track clicks in the new 5.0 UI as well as fix clicks that were not tracked on dropdown menu options in 4.20

**Comment by mheppler** [comment]
With the download btn refactoring spun off into issue **Download Buttons - consolidate render logic #7006**, I am moving this issue forward. Compute btn will be address at another time. Preview btn will be address as part of **Preview Tools - Remove external preview tools connection to Explore btn on dataset/file pgs #6919**.
