### ISSUE TITLE
Dataset Page - File Options Kebab Btn 🍡

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#7081]
Change the file table button style and appearance in the UI to maximum 3 icon buttons (3rd being "kabob" to display additional actions in a dropdown) to add scalability for future file-level actions.

Pulling this out as an individual issue from #6605. Link to mockup: https://www.sketch.com/s/c6f49cf6-795a-4138-931c-fd962ae2542a/a/Emwabv

**Comment by TaniaSchlatter** [comment]
Plan for scaleability is to display not more than 3 action buttons. If there are 4 or more actions, display the "Kebab" icon with a drop down, and include actions 4+ in the dropdown. 

We need to define how this might happen. To what degree should or might this be configurable? For example, what if we prioritize the position of actions?
1. Download/access
2. Preview (go to file page)
3. Edit (for logged in users with permission)
4. Kebab (only if there are 4 or more actions possible)
5. Configure

<img width="770" alt="Screen Shot 2020-07-15 at 12 59 52 PM" src="https://user-images.githubusercontent.com/15386424/87573575-215a0680-c69b-11ea-99c0-0deef8d87c57.png">

**Comment by mheppler** [comment]
Changes to file-level action buttons and messages for the file table on the dataset pg and upload/edit files pg have been outlined in the [File-Level Actions + Messages](https://docs.google.com/document/d/1IDXK3Mur6vCWn2EotORuFdcPePWpcUrAfDcQ7DEfSVQ/edit#) doc. They've been reviewed and approved by the design team, and outlined below. See more detail and screenshots of these changes in that doc.

**TO-DO LIST**

- [ ] Add Access File icon button with dropdown options for Download, Explore, Compute to file-level actions in file table on dataset pg
- [ ] Add Preview icon button which navigates to file pg to file-level actions in file table on dataset pg in support of new Preview external tool type in system configurations (#6919)
- [ ] Style and move ingest info + warning msgs in file-level actions in file table on dataset pg, as well as duplicate content msg on file table on upload/edit files pg
- [ ] Add new file-level edit actions as options under new "kebab" Edit File icon button to file-level actions in file table on dataset pg
- [ ] Move Configure external tools as options under new "kebab" Edit File icon button file-level actions in file table on dataset pg
- [ ] Improve responsive layout and accessibility of the file table on the dataset pg
- [ ] Refactor and consolidate multiple Download button render logic code, move from XHTML to backing bean (#7006)

<img width="641" alt="Screen Shot 2020-08-19 at 11 38 11 AM" src="https://user-images.githubusercontent.com/687227/90656816-7811ad80-e210-11ea-9521-37eccd5ab387.png">

<img width="638" alt="Screen Shot 2020-08-19 at 11 38 28 AM" src="https://user-images.githubusercontent.com/687227/90656946-819b1580-e210-11ea-91ac-6a962504b6f0.png">

<img width="635" alt="Screen Shot 2020-08-19 at 11 38 45 AM" src="https://user-images.githubusercontent.com/687227/90657081-8c55aa80-e210-11ea-8474-eb5bcea7f02e.png">

**Comment by mheppler** [comment]
**Dataset pg**
- [x] add new kebab file options icon btn
- [x] move configure options to new file options dropdown menu
- [x] add configure options dropdown header
- [x] add edit options dropdown header
- [x] add file access icon btn
- [x] move download, explore, compute options to new file access dropdown menu
- [x] style ingest in progress file level info msg
- [x] move, style ingest failed file level warning msg

**Upload/Edit Files pg**
- [x] change edit btn to new kebab file options icon btn
- [x] add edit options dropdown header
- [x] move, style duplicate file name file level warning msg

**File pg**
- [x] move, style ingest failed file level warning msg

**Footer**
- [x] add ``z-index: -1;`` to CSS to fix layering issue with dropdown menus

**_TO-DO_**
- file options btn render logic
- file edit links, render logic, disabled logic to file options dropdown menu
- file access btn render logic
- consolidate download options links under file access dropdown menu
- ? fix rsync access info display in new popup?
- ? fix showAccessFileButtonGroup render logic for no request access/no icon?
- ? request access single dropdown option under new file access "download" icon?

**Comment by mheppler** [comment]
Here are screenshots of the new rsync "Data Access" option under the access file icon btn in the file table on the dataset, plus the new popup displaying the necessary download info.

**NOTE** my localhost is not properly configured, so the Download Access values are empty and displayed blank in the popup screenshot, also hacked the display logic to show the "Data Access" option for a ZIP file as opposed to a Dataverse Package file.

<img width="1149" alt="Screen Shot 2020-09-08 at 12 07 08 PM" src="https://user-images.githubusercontent.com/687227/92512151-5dfa3800-f1dc-11ea-8b85-6d6a0a109997.png">
<img width="607" alt="Screen Shot 2020-09-08 at 12 31 51 PM" src="https://user-images.githubusercontent.com/687227/92512157-605c9200-f1dc-11ea-95dc-5bea4412daad.png">
