### ISSUE TITLE
PM.Epic: Make sure our DDI is valid against the schema

### ISSUE THREAD

**Issue by mreekie** [IQSS/dataverse#8701]
From Leonid
The following issues are about the DDI exporter producing XML that is not valid under the schema. I would consider creating a wider scope umbrella issue, something like "Make sure our DDI is valid against the schema (and maybe add a real time validation step to the export?)

The first one is ready to be worked on, I believe:
- [ ]  https://github.com/IQSS/dataverse/issues/7127 [export]
These *may* need some discussion:
- [ ]  https://github.com/IQSS/dataverse/issues/3648 [export]
- [ ]  https://github.com/IQSS/dataverse/issues/7108 [export]
- [ ]  https://github.com/IQSS/dataverse/issues/8702

The first step in the Harvesting NIH deliverable was figuring out what has already been done by the dataverse team and by the community towards this aim and what still remains to be done. Leonid's conclusions at https://github.com/IQSS/dataverse/issues/8574#issuecomment-1104514775 does that. 

This issue was orginally raised as part of  https://github.com/IQSS/dataverse/issues/8680# . It was broken out as suggested as a seperate epic.

**Comment by mreekie** [comment]
Archiving this.
It does not add any context to the project anymore.

**Comment by mreekie** [comment]
Tentatively adding the issues in this epic to NIH OTA 1.5.1 and re-opening the issues.

**Comment by mreekie** [comment]
Closing issue again.
Talked with Leonid today.
He is going through the issues in #8574 
This is where this issue was originally derived.
Having this issue is redundant since we're taking a fresh look at that whole list.
