### ISSUE TITLE
PM.Epic: (Potentially) Modify the design of the harvesting Framework and/or metadata exports

### ISSUE THREAD

**Issue by mreekie** [IQSS/dataverse#8703]
The following issues are proposed changes to the design of the harvesting framework and/or metadata exports. Meaning this is something we probably need to discuss as a team, before we decide that these are good ideas and proceed to implement them. But IMO they are (I opened all of them 😄): 

- [ ]  https://github.com/IQSS/dataverse/issues/8630 [backend]
- [x]  https://github.com/IQSS/dataverse/issues/8629 [backend]
- [x]  https://github.com/IQSS/dataverse/issues/5960 [backend]
- [ ]  https://github.com/IQSS/dataverse/issues/8631 [backend]
(ordered by importance, IMO)

**Comment by cmbz** [comment]
2025/01/13: Closing as not planned. However, the two remaining issues in the checklist are now identified as potential GREI 3 priorities.
