### ISSUE TITLE
Docs for milestone A of containerization plan

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#9540]
- [x] Explain how to redeploy (the hard way)
- [x] Explain how to view logs ([Slack discussion](https://iqss.slack.com/archives/C010LA04BCG/p1679667714320549?thread_ts=1679663888.250749&cid=C010LA04BCG))
- [x] Update Windows dev page: https://guides.dataverse.org/en/5.13/developers/windows.html
  - A cloned Dataverse by Git for Windows with the line-ending setting is set to always LF (core.autocrlf=input)
- [x] Can use vanilla `docker compose up` instead of `mvn docker:run`: https://preview.guides.gdcc.io/en/develop/container/dev-usage.html
- [x] Explain how to run just the dev_smtp server: `docker-compose -f docker-compose-dev.yml up dev_smtp`
- [x] Explain how to debug
- [x] Explain the different development approaches bare metal, docker, Vagrant and name the preferred one.

I'm giving this our smallest size, 3.
