### ISSUE TITLE
List of linked dataverses in UI and API

### ISSUE THREAD

**Issue by pkiraly** [IQSS/dataverse#9650]
When I worked with dataset links, I found a number of inconsistencies:
- the links are displayed in the dataverse, but they are not displayed in the dataset page
- both the UI and the user documentation of the linking says, that it is not possible to delete a link, the user should contact the site admin. The administration section describes an API of link deletion, but this section is not linked from the above mentioned locations
- the documentation also does not mention any ways how one can get the links via API or SQL commands
- there is an undocumented API for get a list of a particular dataset
- this API returns a semi structured output:

```bash
$ curl -s -H "X-Dataverse-key:$API_TOKEN" $SERVER_URL/api/datasets/56782/links
```
it returns:
```json
{
  "status": "OK",
  "data": {
    "dataverses that link to dataset id 56782": [
      "crc990 (id 18802)"
    ]
  }
}
```
There is an issue which lists related issues (https://github.com/IQSS/dataverse-pm/issues/65). As I checked they covered other problems with the linking, and most of them are not active recently, but it turns that from time to time this group of issues get some focus.

What I suggest here is some small steps, which does not require lots of efforts to make Dataverse a bit more consistent

- [x] 1. add link from the user documentation about linking to the administration documentation about deleting links (PR #9651 - merged)
- [x] 2. document this API (PR #9655)
- [ ] 3. add the list of linked dataverses into the "Link Dataset" form of the dataset page (PR #9661)
- [ ] 4. add the list of linked dataverses into the "Metadata" tab of the dataset page
- [ ] 5. improve the above mentioned link listing API to return a more structured response, something like:
```json
{
  "status": "OK",
  "data": {
    "dataset_id": 56782,
    "linked-dataverses": [
      {"id": 18802, "alias": "crc990"}
    ]
  }
}
```

**Comment by pkiraly** [comment]
@pdurbin Are you with it if I create individual PRs for each of the solutions I listed at the end of the description? Should I create new tickets for them?

**Comment by pdurbin** [comment]
@pkiraly we have a fast track for documentation-only PRs so I would suggest making those first.

**Comment by pdurbin** [comment]
@pkiraly thanks for breaking this down into smaller chunks!

Can you please look at this issue?

- #9733

Do you want that as well?
